[package]
name = "audity"
version = "0.1.0"
edition = "2024"

[dependencies]
serde      = { version = "1.0", features = ["derive"] }
quick-xml  = { version = "0.30", features = ["serialize"] } # depuis 0.30, la même feature active (de)Serialize
thiserror  = "1.0"